server:
  port: 8088

security:
  basic:
    enabled: "${SECURITY_ENABLED:true}"
  user:
    name: "admin"
    password: "admin"

spring:
  session:
    enabled: "${SESSION_CLUSTER_ENABLED:true}"
  datasource:
    url: "jdbc:postgresql://localhost:5432/iat"
    username: "${DB_USER}"
    password: "${DB_PASSWORD}"
    validationQuery: "SELECT 1"
    max-active: 5

itembank:
  host: "https://gitlab-dev.smarterbalanced.org"
  accessToken: "${GITLAB_ACCESS_TOKEN}"
  user: "${GITLAB_USER}"
  password: "${GITLAB_PASSWORD}"
  group: "${GITLAB_GROUP}"
  # -------- START PRODUCTION ---------
  #  host: ""
  #  accessToken: ""
  #  user: ""
  #  password: ""
  #  group: ""
  # -------- END PRODUCTION ---------
  localBaseDir: "${HOME}/ItemBankMigration"
  apiVersion: "/api/v4"
  bankKey: "200"
  # the system version does not do anything when running locally, the set key is what is used/saved on the entity
  systemVersion: "iat-31.1"
  reportRepoName: "ItemBankReports"
  randomizeItemClone: true       #set true for migration; false for download
  resultsPerPageFindingAllItems: "250"
  enabled:
    database: true
    broker: true
    producer: true
  aws:
    endpointUrl: "https://s3.us-east-2.amazonaws.com"
    region: "us-east-2"
    bucketName: "${itembank.group}"
    accessKey: "${IAT_AWS_ACCESS_KEY}"
    secretKey: "${IAT_AWS_ACCESS_SECRET}"

logging:
  level:
    org:
      opentestsystem:
        ap:
          migration: "debug"
          common: "info"

migration:
  numberOfThreads: 5
  publishReportEnabled: true
  syncFromGitlabEnabled: false
  includedItems:
#  - 94351
#  - 95548
  data-store-migrations:
    enabled: true
    migrationSets:
#    - migrationSetKey: "iat-30"
#      migrationDefinitions:
#      - migrationName: "migration2225"
#        migrationDescription: "Migration: Rename ASL files to have STEM at the end."
#      - migrationName: "migration2119"
#        migrationDescription: "Migration: Map WER rubric from plain text to rich text."
      - migrationSetKey: "iat-31"
        migrationDefinitions:
          - migrationName: "migration2576"
            migrationDescription: "Migration: Update imported item glossary values."
          - migrationName: "migration2669"
            migrationDescription: "Migration2669: Update items' server managed values"
          - migrationName: "migration2698"
            migrationDescription: "Migration2698: Update glossary audio file names"
          - migrationName: "migrationGenerateSaaif"
            migrationDescription: "Migration2133: Update Nested tables."
          - migrationName: "migrationGenerateSaaif"
            migrationDescription: "Migration1686: Add Braille values to metadata file."
          - migrationName: "migrationGenerateSaaif"
            migrationDescription: "Migration2542: Update TTS for images."
          - migrationName: "migrationGenerateSaaif"
            migrationDescription: "Migration2690: Add intended grade to the SAAIF item content XML file"
          - migrationName: "migrationGenerateSaaif"
            migrationDescription: "Migration2691: Add spa language in the SAAIF metadata.xml"
          - migrationName: "migrationGenerateSaaif"
            migrationDescription: "Migration2693: Add subject to the SAAIF item content XML file"
          - migrationName: "migrationGenerateSaaif"
            migrationDescription: "Migration2711: Create translation TTS tags in the SAAIF item content XML file"
      - migrationSetKey: "iat-34"
        migrationDefinitions:
          - migrationName: "migration2673"
            migrationDescription: "Migration2673: Set correct item prompt on imported EBSR items"
          - migrationName: "migration2641"
            migrationDescription: "IAT-2641: Prepend any Stimulus title field values to the existing prompt"
            migrateBranches: true
          - migrationName: "migration2785"
            migrationDescription: "Migration2785: Set correct item version on imported items"
            migrateBranches: true
          - migrationName: "migration2619"
            migrationDescription: "Migration2619: Populate MC options on imported items"
            migrateBranches: true
          - migrationName: "migration2624"
            migrationDescription: "Migration2624: Table was stripped out of item prompt during import"
            migrateBranches: true
          - migrationName: "migration2668"
            migrationDescription: "migration2668: Update EBSR, MC and MS options to not stack spanish when they only contain images"
            migrateBranches: true
          - migrationName: "migration2657"
            migrationDescription: "IAT-2657: IAT-2790: Process audio references from anchor tags"
            migrateBranches: true
          - migrationName: "migration2571"
            migrationDescription: "Migration2571: Imported braille file names need to be updated to reference the new item ID and regex pattern"
            migrateBranches: true
          - migrationName: "migration2659"
            migrationDescription: "Migration2659: CC file names will need to be updated to match newly imported Item ID and associated to their items"
            migrateBranches: true
          - migrationName: "migration2660"
            migrationDescription: "Migration2660: Image file names will need to be updated to match newly imported Item ID and associated to their items"
            migrateBranches: true
          - migrationName: "migration2670"
            migrationDescription: "Migration2670: Image TTS tags were lost during import"
            migrateBranches: true
          - migrationName: "migration2593"
            migrationDescription: "Migration2593: English text not removed from translations content in TI items"
            migrateBranches: true
          - migrationName: "migration2750"
            migrationDescription: "Migration2750: QRX files were not imported to certain items"
            migrateBranches: true
          - migrationName: "migration2642"
            migrationDescription: "Migration2642: Set TTS metadata values"
            migrateBranches: true
          - migrationName: "migration2655"
            migrationDescription: "Migration2655: Import cleanup: Glossary m4a audio files did not import properly"
            migrateBranches: true
          - migrationName: "migration2751"
            migrationDescription: "Migration2751: Import cleanup: Some attachments were not copied during import due to file extension capitalization"
            migrateBranches: true
          - migrationName: "migration2605"
            migrationDescription: "Migration2605: Import cleanup: Editing an imported glossary term that has rich text formatting applied loses link to glossary entry"
            migrateBranches: true
          - migrationName: "migration2792"
            migrationDescription: "Migration2792: Set Scoring engine to AutomaticWithKeys on imported MS and EBSR items"
            migrateBranches: true
          - migrationName: "migration2799"
            migrationDescription: "Migration2799: MI item(s) lost the correct answers during import"
            migrateBranches: true
          - migrationName: "migration2660"
            migrationDescription: "Migration2660: Image file names will need to be updated to match newly imported Item ID and associated to their items"
            migrateBranches: true
          - migrationName: "migration2729"
            migrationDescription: "IAT-2729: Change TIMS-created item repository names & file names to match downstream system needs"
          - migrationName: "migration2708"
            migrationDescription: "Migration2708: Score points validation error regarding quotes is generated against items with points assigned"
            migrateBranches: true
          - migrationName: "migration1615"
            migrationDescription: "IAT-1615: Update image TTS html markup on rich text fields"
            migrateBranches: true
          - migrationName: "migration2360"
            migrationDescription: "IAT-2360: Update invalid Scoring Engine metadata values"
            migrateBranches: true
          - migrationName: "migration2776"
            migrationDescription: "IAT-2776: Remove certain html style values from imported items"
            migrateBranches: true
          - migrationName: "migration2805"
            migrationDescription: "Migration2805: Set correct item prompt on imported EBSR items"
            migrateBranches: true
          - migrationName: "migration2815"
            migrationDescription: "IAT-2815: Validation: Both HTQ item types fail item type validation"
          - migrationName: "migrationGenerateSaaif"
            migrationDescription: "IAT-2364/IAT-2810: SAAIF files contain translation content for all items even when no translations are defined"
          - migrationName: "migrationGenerateSaaif"
            migrationDescription: "IAT-2662: Validation: Translated glossary errors are generated against terms with english only definitions"
          - migrationName: "migration2701"
            migrationDescription: "migration2701: The saved metadata value for Primary Emphasis is incorrect (n/a should be NA)"
            migrateBranches: true
          - migrationName: "migration2560"
            migrationDescription: "IAT-2560: HTQS does not have a space between the prompt and the interactive text"
          - migrationName: "migration2863"
            migrationDescription: "IAT-2863: Import Cleanup: Some prompt text is missing spacing"
          - migrationName: "migration2807"
            migrationDescription: "Migration2807: Validation: Duplicate attachment ID error on migrated braille files"
          - migrationName: "migration2788"
            migrationDescription: "migration2788: Uploading ASL files lowercases their names breaking ASL."
            migrateBranches: true
          - migrationName: "migration2313Htqs"
            migrationDescription: "migration2313Htqs: Import rubric value, import qrx file and set interactive text to be non-editable until user discards imported values"
            migrateBranches: true
          - migrationName: "migration2313NonHtqs"
            migrationDescription: "Migration2313NonHtqs: Set Scoring.isManagedByIat and Scoring.machineScoringManagedByIat to true"
            migrateBranches: true
      - migrationSetKey: "iat-35"
        migrationDefinitions:
          - migrationName: "migration2777"
            migrationDescription: "IAT-2777: Validation: Error regarding empty stimulus values generated against items with linked stim"
          - migrationName: "migrationGenerateSaaif"
            migrationDescription: "IAT-2362: Validation: Attachment error generated despite no attachments existing on item"
          - migrationName: "migration2483"
            migrationDescription: "Migration2483: Some imported items don't show table cell borders when previewed"
            migrateBranches: true
---
spring:
  profiles: dev
  datasource:
    url: "jdbc:postgresql://imrt-qa-db.cjqp2fdamfoh.us-east-2.rds.amazonaws.com:5432/iat"
    max-active: 2

itembank:
  group: "iat-development"

---
spring:
  profiles: prod-mirror
  datasource:
    url: "jdbc:postgresql://tims-prod-mirror.cjqp2fdamfoh.us-east-2.rds.amazonaws.com:5432/iat"
    max-active: 2

itembank:
  group: "iat-prod-mirror"
