# --------------------------------------------------------
# These properties are the local development properties.
#
# Spring boot uses this file when the application is launched
# with the root of the project set as the working directory.
# These properties take precendence over the classpath
# application.yml.
#
# Using gradle from the commandline means the working
# directory is by defaul the project root.
#
# Using Intellij you need to setup your run config so the
# working directory is the project root.
# --------------------------------------------------------
server:
  port: 8088

security:
  basic:
    enabled: "${SECURITY_ENABLED:true}"
  user:
    name: "admin"
    password: "admin"

spring:
  session:
    enabled: "${SESSION_CLUSTER_ENABLED:true}"

itembank:
  host: "https://gitlab-dev.smarterbalanced.org"
  accessToken: "${GITLAB_ACCESS_TOKEN}"
  user: "${GITLAB_USER}"
  password: "${GITLAB_PASSWORD}"
  group: "${GITLAB_GROUP}"
  localBaseDir: "${HOME}/ItemBank"
  apiVersion: "/api/v4"
  bankKey: "187"
  systemVersion: "iat-5"
  reportRepoName: "ItemBankReports"

logging:
  level:
    org:
      opentestsystem:
        ap:
          migration: "debug"
          common: "info"

migration:
  systemUsername: "item-migration@smarterbalanced.org"
  systemFullname: "Item Migration"
#  includedItems:
#    - 200004
  deleteItemsEnabled: true
  doNotDeleteItems:
    - 200000
    - 7221
    - 7220
  migrationsEnabled: false
  migrationSets:
    -
      migrationSetKey: "iat-4"
      migrationDefinitions:
        -
          migrationName: "migration1611"
          migrationDescription: "Migration: set all items to Draft workflow status"
        -
          migrationName: "migrationEmpty"
          migrationDescription: "Migration: increment item version to iat-4"
    -
      migrationSetKey: "iat-5"
      migrationDefinitions:
        -
          migrationName: "migrationEmpty"
          migrationDescription: "Migration: increment item version to iat-5"





