# --------------------------------------------------------
# These properties are the local development properties.
#
# Spring boot uses this file when the application is launched
# with the root of the project set as the working directory.
# These properties take precedence over the classpath
# application.yml.
#
# Using gradle from the commandline means the working
# directory is by default the project root.
#
# Using Intellij you need to setup your run config so the
# working directory is the project root.
# --------------------------------------------------------
server:
  port: 8088

security:
  basic:
    enabled: "${SECURITY_ENABLED:true}"
  user:
    name: "admin"
    password: "admin"

spring:
  session:
    enabled: "${SESSION_CLUSTER_ENABLED:true}"

itembank:
  host: "https://gitlab-dev.smarterbalanced.org"
  accessToken: "${GITLAB_ACCESS_TOKEN}"
  user: "${GITLAB_USER}"
  password: "${GITLAB_PASSWORD}"
#  group: "${GITLAB_GROUP}"
#  group: "iat-alex"
  group: "iat-development"
#  group: "iat-uat"
# -------- PRODUCTION ---------
#  host: "https://itembank.smarterbalanced.org"
#  accessToken: ""
#  user: "ap-system-user"
#  password: ""
#  group: "iat-prod"
  localBaseDir: "${HOME}/ItemBankMigration"
  apiVersion: "/api/v4"
  bankKey: "187"
  systemVersion: "iat-11"
  reportRepoName: "ItemBankReports"
  randomizeItemClone: true #set true for migration; false for download
  resultsPerPageFindingAllItems: "250"
  restrictToBranchOwner: false

logging:
  level:
    org:
      opentestsystem:
        ap:
          migration: "debug"
          common: "info"

migration:
  systemUsername: "item-migration@smarterbalanced.org"
  systemFullname: "Item Migration"
  deleteItemsEnabled: false
  downloadItemsEnabled: false
  migrationsEnabled: true
  publishReportEnabled: true
  includedItems:
    - 205629
  migrationSets:
    -
      migrationSetKey: "iat-8.1"
      migrationDefinitions:
        -
          migrationName: "migration1484"
          migrationDescription: "Migration: update metadata field names"
    -
      migrationSetKey: "iat-10"
      migrationDefinitions:
        -
          migrationName: "migration1703"
          migrationDescription: "Migration: update layout attribute for items with no associated stimulus"
    -
      migrationSetKey: "iat-11.1"
      migrationDefinitions:
        -
          migrationName: "migration1826"
          migrationDescription: "Migration: reformatting SAAIF files"
    -
      migrationSetKey: "iat-11.2"
      migrationDefinitions:
        -
          migrationName: "migration1827"
          migrationDescription: "Migration1827: Recover primaryContentDomain value from item history"