server:
  port: 8088

security:
  basic:
    enabled: "${SECURITY_ENABLED:true}"
  user:
    name: "admin"
    password: "admin"

spring:
  session:
    enabled: "${SESSION_CLUSTER_ENABLED:true}"
  datasource:
    url: "jdbc:postgresql://localhost:5432/iat"
    username: "${DB_USER}"
    password: "${DB_PASSWORD}"
    validationQuery: "SELECT 1"

itembank:
  host: "https://gitlab-dev.smarterbalanced.org"
  accessToken: "${GITLAB_ACCESS_TOKEN}"
  user: "${GITLAB_USER}"
  password: "${GITLAB_PASSWORD}"
  group: "${GITLAB_GROUP}"
  # -------- START PRODUCTION ---------
  #  host: ""
  #  accessToken: ""
  #  user: ""
  #  password: ""
  #  group: ""
  # -------- END PRODUCTION ---------
  localBaseDir: "${HOME}/ItemBankMigration"
  apiVersion: "/api/v4"
  bankKey: "187"
  systemVersion: "iat-25"
  reportRepoName: "ItemBankReports"
  randomizeItemClone: true       #set true for migration; false for download
  resultsPerPageFindingAllItems: "250"
  enabled:
    database: true
    broker: true
    producer: true
  aws:
    endpointUrl: "https://s3.us-east-2.amazonaws.com"
    region: "us-east-2"
    bucketName: "${itembank.group}"
    accessKey: "${IAT_AWS_ACCESS_KEY}"
    secretKey: "${IAT_AWS_ACCESS_SECRET}"

logging:
  level:
    org:
      opentestsystem:
        ap:
          migration: "debug"
          common: "info"

migration:
  numberOfThreads: 5
  publishReportEnabled: true
  includedItems:
#  - 208183
  data-store-migrations:
    enabled: true
    migrationSets:
    - migrationSetKey: "iat-24"
      migrationDefinitions:
      - migrationName: "migration2225"
        migrationDescription: "Migration: Rename ASL files to have STEM at the end."
    - migrationSetKey: "iat-25"
      migrationDefinitions:
      - migrationName: "migration2119"
        migrationDescription: "Migration: Map WER rubric from plain text to rich text."
    - migrationSetKey: "iat-26"
      migrationDefinitions:
      - migrationName: "migration2119"
        migrationDescription: "Migration: Map WER rubric from plain text to rich text."
        broadcast: false
      - migrationName: "migration2442"
        migrationDescription: "Migration: Regenerate SAAIF files."
---
spring:
  profiles: dev
  datasource:
    url: "jdbc:postgresql://imrt-qa-db.cjqp2fdamfoh.us-east-2.rds.amazonaws.com:5432/iat"

itembank:
  group: "iat-development"
