server:
  port: 8088

security:
  basic:
    enabled: "${SECURITY_ENABLED:true}"
  user:
    name: "admin"
    password: "admin"

spring:
  session:
    enabled: "${SESSION_CLUSTER_ENABLED:true}"
  datasource:
    url: "jdbc:postgresql://localhost:5432/iat"
    username: "${DB_USER}"
    password: "${DB_PASSWORD}"
    validationQuery: "SELECT 1"

itembank:
  host: "https://gitlab-dev.smarterbalanced.org"
  accessToken: "${GITLAB_ACCESS_TOKEN}"
  user: "${GITLAB_USER}"
  password: "${GITLAB_PASSWORD}"
  group: "${GITLAB_GROUP}"
  # -------- START PRODUCTION ---------
  #  host: ""
  #  accessToken: ""
  #  user: ""
  #  password: ""
  #  group: ""
  # -------- END PRODUCTION ---------
  localBaseDir: "${HOME}/ItemBankMigration"
  apiVersion: "/api/v4"
  bankKey: "200"
  # the system version does not do anything when running locally, the set key is what is used/saved on the entity
  systemVersion: "iat-31.1"
  reportRepoName: "ItemBankReports"
  randomizeItemClone: true       #set true for migration; false for download
  resultsPerPageFindingAllItems: "250"
  enabled:
    database: true
    broker: true
    producer: true
  aws:
    endpointUrl: "https://s3.us-east-2.amazonaws.com"
    region: "us-east-2"
    bucketName: "${itembank.group}"
    accessKey: "${IAT_AWS_ACCESS_KEY}"
    secretKey: "${IAT_AWS_ACCESS_SECRET}"

logging:
  level:
    org:
      opentestsystem:
        ap:
          migration: "debug"
          common: "info"

migration:
  numberOfThreads: 5
  publishReportEnabled: true
  syncFromGitlabEnabled: false
  includedItems:
  - 102955
  data-store-migrations:
    enabled: true
    migrationSets:
#    - migrationSetKey: "iat-24"
#      migrationDefinitions:
#      - migrationName: "migration2225"
#        migrationDescription: "Migration: Rename ASL files to have STEM at the end."
#    - migrationSetKey: "iat-25"
#      migrationDefinitions:
#      - migrationName: "migration2119"
#        migrationDescription: "Migration: Map WER rubric from plain text to rich text."
#    - migrationSetKey: "iat-26"
#      migrationDefinitions:
#      - migrationName: "migration2119"
#        migrationDescription: "Migration: Map WER rubric from plain text to rich text."
#        broadcast: false
#    - migrationSetKey: "iat-27"
#      migrationDefinitions:
#      - migrationName: "migration2576"
#        migrationDescription: "Migration: Update imported item glossary values."
#    - migrationSetKey: "iat-28"
#      migrationDefinitions:
#      - migrationName: "migrationGenerateSaaif"
#        migrationDescription: "Migration2133: Update Nested tables."
#    - migrationSetKey: "iat-29"
#      migrationDefinitions:
#      - migrationName: "migrationGenerateSaaif"
#        migrationDescription: "Migration1686: Add Braille values to metadata file."
#    - migrationSetKey: "iat-30"
#      migrationDefinitions:
#      - migrationName: "migrationGenerateSaaif"
#        migrationDescription: "Migration2542: Update TTS for images."
#    - migrationSetKey: "iat-30.1"
#      migrationDefinitions:
#        - migrationName: "migration2669"
#          migrationDescription: "Migration2669: Update items' server managed values"
#    - migrationSetKey: "iat-30.2"
#      migrationDefinitions:
#        - migrationName: "migrationGenerateSaaif"
#          migrationDescription: "Migration2690: Add intended grade to the SAAIF item content XML file"
#        - migrationName: "migrationGenerateSaaif"
#          migrationDescription: "Migration2691: Add spa language in the SAAIF metadata.xml"
#        - migrationName: "migrationGenerateSaaif"
#          migrationDescription: "Migration2693: Add subject to the SAAIF item content XML file"
#        - migrationName: "migrationGenerateSaaif"
#          migrationDescription: "Migration2711: Create translation TTS tags in the SAAIF item content XML file"
#    - migrationSetKey: "iat-31.1"
#      migrationDefinitions:
#        - migrationName: "migration2673"
#          migrationDescription: "Migration2673: Set correct item prompt on imported EBSR items"
#    - migrationSetKey: "iat-31.2"
#      migrationDefinitions:
#        - migrationName: "migration2785"
#          migrationDescription: "Migration2785: Set correct item version on imported items"
#    - migrationSetKey: "iat-31.3"
#      migrationDefinitions:
#        - migrationName: "migration2641"
#          migrationDescription: "IAT-2641: Prepend any Stimulus title field values to the existing prompt"
#    - migrationSetKey: "iat-31.4"
#      migrationDefinitions:
#        - migrationName: "migration2657"
#          migrationDescription: "IAT-2657: IAT-2790: Process audio references from anchor tags"
#          migrateBranches: true
#    - migrationSetKey: "iat-31.5"
#      migrationDefinitions:
#        - migrationName: "migration2619"
#          migrationDescription: "Migration2619: Populate MC options on imported items"
#          migrateBranches: true
#    - migrationSetKey: "iat-31.6"
#      migrationDefinitions:
#        - migrationName: "migration2624"
#          migrationDescription: "Migration2624: Table was stripped out of item prompt during import"
#          migrateBranches: true
#    - migrationSetKey: "iat-31.7"
#      migrationDefinitions:
#        - migrationName: "migration2670"
#          migrationDescription: "Migration2670: Image TTS tags were lost during import"
#          migrateBranches: true
#    - migrationSetKey: "iat-31.8"
#      migrationDefinitions:
#        - migrationName: "migration2571"
#          migrationDescription: "Migration2571: Imported braille file names need to be updated to reference the new item ID and regex pattern"
#          migrateBranches: true
#    - migrationSetKey: "iat-31.9"
#      migrationDefinitions:
#        - migrationName: "migration2658"
#          migrationDescription: "Migration2658: ASL file names will need to be updated to match newly imported Item ID and associated to their items"
#          migrateBranches: true
#    - migrationSetKey: "iat-31.11"
#      migrationDefinitions:
#        - migrationName: "migration2660"
#          migrationDescription: "Migration2660: Image file names will need to be updated to match newly imported Item ID and associated to their items"
#          migrateBranches: true
#    - migrationSetKey: "iat-31.11"
#      migrationDefinitions:
#        - migrationName: "migration2659"
#          migrationDescription: "Migration2659: CC file names will need to be updated to match newly imported Item ID and associated to their items"
#          migrateBranches: true
#    - migrationSetKey: "iat-31.12"
#      migrationDefinitions:
#        - migrationName: "migration2593"
#          migrationDescription: "Migration2593: English text not removed from translations content in TI items"
#          migrateBranches: true
#    - migrationSetKey: "iat-31.13"
#      migrationDefinitions:
#        - migrationName: "migration2750"
#          migrationDescription: "Migration2750: QRX files were not imported to certain items"
#          migrateBranches: true#
#    - migrationSetKey: "iat-31.26"
#      migrationDefinitions:
#        - migrationName: "migration2656"
#          migrationDescription: "Migration2656: correct imported braille file subtypes"
#          migrateBranches: true
#    - migrationSetKey: "iat-31.14"
#      migrationDefinitions:
#        - migrationName: "migration2642"
#          migrationDescription: "Migration2642: Set TTS metadata values"
#          migrateBranches: true
#    - migrationSetKey: "iat-31.15"
#      migrationDefinitions:
#        - migrationName: "migration2597"
#          migrationDescription: "Migration2597: Tutorial/ASL previewing intermittently"
#          migrateBranches: true
#    - migrationSetKey: "iat-31.16"
#      migrationDefinitions:
#        - migrationName: "migration2723"
#          migrationDescription: "Migration2723: Re-import 409 items that didn't sync to GitLab during initial import"
#          migrateBranches: true
#    - migrationSetKey: "iat-31.17"
#      migrationDefinitions:
#        - migrationName: "migration2655"
#          migrationDescription: "Migration2655: Import cleanup: Glossary m4a audio files did not import properly"
#          migrateBranches: true
#    - migrationSetKey: "iat-31.18"
#      migrationDefinitions:
#        - migrationName: "migration2751"
#          migrationDescription: "Migration2751: Import cleanup: Some attachments were not copied during import due to file extension capitalization"
#          migrateBranches: true
#    - migrationSetKey: "iat-31.19"
#      migrationDefinitions:
#        - migrationName: "migration2608"
#          migrationDescription: "Migration2608: Import: 404 errors when previewing TI and MS items imported to production"
#          migrateBranches: true
#    - migrationSetKey: "iat-31.20"
#      migrationDefinitions:
#        - migrationName: "migration2620"
#          migrationDescription: "Migration2620: Import Cleanup: Cannot read property 'changedOn' of undefined during preview"
#          migrateBranches: true
#    - migrationSetKey: "iat-31.21"
#      migrationDefinitions:
#        - migrationName: "migration2572"
#          migrationDescription: "Migration2572: Import cleanup: Ability to view Tutorial is missing in the menu when previewing items with translations"
#          migrateBranches: true
#    - migrationSetKey: "iat-31.22"
#      migrationDefinitions:
#        - migrationName: "migration2638"
#          migrationDescription: "Migration2638: Some metadata fields display null values in search results but those fields have values in IAT"
#          migrateBranches: true
#    - migrationSetKey: "iat-31.23"
#      migrationDefinitions:
#        - migrationName: "migration2629"
#          migrationDescription: "Migration2629: Import: Metadata values not mapped correctly on items with more than one ELA standard publication"
#          migrateBranches: true
#    - migrationSetKey: "iat-31.24"
#      migrationDefinitions:
#        - migrationName: "migration2605"
#          migrationDescription: "Migration2605: Import cleanup: Editing an imported glossary term that has rich text formatting applied loses link to glossary entry"
#          migrateBranches: true
#    - migrationSetKey: "iat-31.25"
#      migrationDefinitions:
#        - migrationName: "migration2567"
#          migrationDescription: "Migration2567: Import cleanup: MC and MS Options get misaligned if previewing with translations enabled"
#          migrateBranches: true
#    - migrationSetKey: "iat-31.26"
#      migrationDefinitions:
#        - migrationName: "migration2656"
#          migrationDescription: "Migration2656: Import Cleanup: 14k imported items have wrong Braille sub-type"
#          migrateBranches: true
#    - migrationSetKey: "iat-31.28"
#      migrationDefinitions:
#        - migrationName: "migration2792"
#          migrationDescription: "Migration2792: Set Scoring engine to AutomaticWithKeys on imported MS and EBSR items"
#          migrateBranches: true
#    - migrationSetKey: "iat-31.29"
#      migrationDefinitions:
#        - migrationName: "migration2669Htqo"
#          migrationDescription: "Migration2669Htqo: HTQO items are missing prompt data"
#          migrateBranches: true
#    - migrationSetKey: "iat-31.30"
#      migrationDefinitions:
#        - migrationName: "migration2799"
#          migrationDescription: "Migration2799: MI item(s) lost the correct answers during import"
#          migrateBranches: true
#    - migrationSetKey: "iat-31.33"
#      migrationDefinitions:
#        - migrationName: "migration2805"
#          migrationDescription: "Migration2805: Set correct item prompt on imported EBSR items"
#          migrateBranches: true

# These migrations requires the use of ap_common version 0.4.107 or higher
#    - migrationSetKey: "iat-31.27"
#      migrationDefinitions:
#        - migrationName: "migration2668"
#          migrationDescription: "Migration2668: Remove images from translated item options if they are identical to the english image names. \nMigration2567: MC and MS Options get misaligned if previewing with translations enabled"
#          migrateBranches: true
#        - migrationName: "migration2708"
#          migrationDescription: "Migration2708: Score points validation error regarding quotes is generated against items with points assigned"
#          migrateBranches: true
#    - migrationSetKey: "iat-32"
#      migrationDefinitions:
#        - migrationName: "migration2729"
#          migrationDescription: "IAT-2729: Change TIMS-created item repository names & file names to match downstream system needs"
    - migrationSetKey: "iat-35"
      migrationDefinitions:
        - migrationName: "migration1615"
          migrationDescription: "IAT-1615: Update image TTS values"
---
spring:
  profiles: dev
  datasource:
    url: "jdbc:postgresql://imrt-qa-db.cjqp2fdamfoh.us-east-2.rds.amazonaws.com:5432/iat"

itembank:
  group: "iat-development"
