# --------------------------------------------------------
# These properties are the local development properties.
#
# Spring boot uses this file when the application is launched
# with the root of the project set as the working directory.
# These properties take precedence over the classpath
# application.yml.
#
# Using gradle from the commandline means the working
# directory is by default the project root.
#
# Using Intellij you need to setup your run config so the
# working directory is the project root.
# --------------------------------------------------------
server:
  port: 8088

security:
  basic:
    enabled: "${SECURITY_ENABLED:true}"
  user:
    name: "admin"
    password: "admin"

spring:
  session:
    enabled: "${SESSION_CLUSTER_ENABLED:true}"
  autoconfigure:
    exclude:
    - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
    - org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration
    - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
    - org.springframework.boot.autoconfigure.jdbc.JdbcTemplateAutoConfiguration

itembank:
  host: "https://gitlab-dev.smarterbalanced.org"
  accessToken: "${GITLAB_ACCESS_TOKEN}"
  user: "${GITLAB_USER}"
  password: "${GITLAB_PASSWORD}"
  group: "${GITLAB_GROUP}"
#  group: "iat-development"
#  group: "iat-uat"
# -------- START PRODUCTION ---------
#  host: ""
#  accessToken: ""
#  user: ""
#  password: ""
#  group: ""
# -------- END PRODUCTION ---------
  localBaseDir: "${HOME}/ItemBankMigration"
  apiVersion: "/api/v4"
  bankKey: "187"
  systemVersion: "iat-17"
  reportRepoName: "ItemBankReports"
  randomizeItemClone: true       #set true for migration; false for download
  resultsPerPageFindingAllItems: "250"

logging:
  level:
    org:
      opentestsystem:
        ap:
          migration: "debug"
          common: "info"

migration:
  systemUsername: "item-migration@smarterbalanced.org"
  systemFullname: "Item Migration"
  deleteItemsEnabled: false
  downloadItemsEnabled: false
  migrationsEnabled: true
  publishReportEnabled: true
  numberOfThreads: 10
  includedItems:
    - 1284
    - 1283
    - 1282
    - 1281
    - 1280
    - 1276
    - 1275
    - 1274
    - 1273
    - 1268
    - 1267
    - 1266
    - 1264
    - 1262
    - 1261
    - 1260
  migrationSets:
    -
      migrationSetKey: "iat-17"
      migrationDefinitions:
        -
          migrationName: "migration1764"
          migrationDescription: "Migration: Update SpecificationsVersion metadata field"